config/routes.rb
Rails.application.routes.draw do
  root 'companies#index'
  resources :companies do
   collection do
    #get :search
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/companie.rb
class Companie < ApplicationRecord

 include Elasticsearch::Model
 include Elasticsearch::Model::Callbacks  
 
 #  def self.search(query)
 #    __elasticsearch__.search(
 #    {
 #        query: {
 #          from: 1,
 #          size: 25,
 #          multi_match: {
 #          query: query,
 #          type: 'phrase',
 #          fields: ['company_name^5', 'technology','experience','position']
 #        },
 #    }
 # end
end

#  __elasticsearch__.search(
#     {  
#        "size":"15",
#         "query": {
#           "multi_match": {
#           "query": "query",
#           "fields": ["company_name","technology","experience" ,"position"]
#         }
#     }
# })

app/models/product.rb
class Product < ApplicationRecord
	include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  #Elasticsearch::Model.search(size: 50)
#     def self.product(query)  
#     __elasticsearch__.search(
#      {  
#       "from": "0",
#        "size": "19",
#         "query": {
#           "multi_match": {
#           "query": "query",
#           "fields": ["company_name" "technology" "experience"  "position"]
#         }
#     }
# })

 #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	#include Rails::Pagination
    #Elasticsearch::Model.search(query, [], size: 20)
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	def index
	 #@companies = Companie.all
	  #@companies =  Companie.search(params[:query].presence ? params[:query] : '*').records
	# @products = Product.paginate(page: params[:page])
     @products = Product.search(params[:query].presence ? params[:query] : '*', size: 500).records
    # @products  = Product.paginate(:page => params[:page], :per_page=>17)
	end

	# def new
	#   @companies = Companie.new
	# end

	# def create
	#  @companies = Companie.new(companie_params)
	#  if@companies.save
	#    redirect_to root_path, notice: "created successfullly"
	#  else
	# 	render :new, notice: "Please enter all the details"
	#  end
 #    end

 # #   def search
	# #   query = params[:query]
	# #   if query
	# #   	debugger
	# #    # @companies = Companie.search_published(query)
	# #      @companies=Companie.search_published(params[:query])
	# #      @companies =  Companie.all.search(params[:query].presence ? params[:query] : '*').records

	# #   end
	# # end

 #    private

 #    def companie_params
 #    	params.require(:companie).permit(:company_name, :job_title, :position, :experience)
   #end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/index.html.erb
<center><%#= link_to 'add jobs',new_company_path%></center>


      <center><h1>Welcome to Elastic search Job Web portal</h1></center>

<%#= form_for :search_companies, search_companies_path, method: :get do |form| %>
<%= form_tag  companies_path, role: "search", method: :get do %>
<%= text_field_tag :query , params[:query]%>
<%= button_tag 'Search',name: nil,class: "btn btn-default btn-primary" %></center>
<% end %>

<% unless @products.nil? %>
  <% if @products.empty? %>
    <center><h2>Sorry no Comapnies found</h2></center>
  <% else %>
    <h2>Search results</h2>
    </table>
    <%end%>
     <%end%>
<table style="width: 100%;">
      <thead>
         <tr>
           <th>company_name</th>
           <th>technology</th>
           <th>experience</th>
           <th>position</th>
    
         </tr>
      </thead>

      <tbody>
        <%  @products.each do |p| %>
          <tr>
           <td><%= p.company_name %></td>
            <td><%= p.technology %></td>
            <td><%= p.experience%></td>
            <td><%= p.position%></td>
         
                <td><%#= link_to 'View',   company_path(company.id) %></td>
          </tr>
        <% end %>
         <%#=will_paginate @products %>
        
      <tbody>
    </table>

app/views/companies/new.html.erb
<%#= form_with model: @companies do |form|%>
<div>
	 <%#=form.label :company_name%>
	 <%#=form.text_field :company_name %>
</div>
<div>
	 <%#=form.label :job_title%>
	 <%#=form.text_field :job_title %>
</div>
 <div>
	 <%#=form.label :experience%>
	 <%#=form.text_field :experience%>
 </div>
 <div>
	 <%#=form.label :position%>
	 <%#=form.text_field :position %>
 </div>
 <div>
    <%#=form.submit%>
</div>
<%#end%>
 @products = Product.search(params[:query].presence ? params[:query] : '*',size: 500

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
 </head>

  <body>
  
     <%= flash[:alert] %>
     <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>